basic:
  path_type: "module"
  description: "simplest mock request sample"

target_request:
  srcfile: "kumonote/sandbox/data/sample-requests.yaml"
  loader: "kumonote.loader:YAMLLoader"
  builder: "kumonote.sandbox.testing:MockRequestTreeBuilder"

driver:
  main: "kumonote.sandbox.drivers:main"
  loop: "asyncio:get_event_loop"
  loop_main: "kumonote.sandbox.drivers.wait_each_request:do_loop_single_chain"
  fetcher: "kumonote.sandbox.fetching:Fetcher"

fetcher:
  get_key: "kumonote.sandbox.testing:get_domain"
  get_response: "kumonote.sandbox.testing:get_response"

logging:
  format: "%(asctime)s %(message)s"
  level: "DEBUG"
